/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    application
}

repositories {
    maven {
        url = uri("https://jitpack.io")
    }
    maven {
        url = uri("https://repo.md-5.net/content/groups/public/")
    }
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }
    maven {
        url = uri("https://nexus.hc.to/content/repositories/pub_releases")
    }
    maven {
        url = uri("https://maven.enginehub.org/repo/")
    }
    maven {
        url = uri("https://ci.ender.zone/plugin/repository/everything/")
    }
    maven {
        url = uri("https://repo.minebench.de/")
    }
    maven {
        url = uri("https://repo.codemc.org/repository/maven-public")
    }
    maven {
        url = uri("https://mvn.lumine.io/repository/maven/")
    }
    maven {
        url = uri("https://nexus.lichtspiele.org/repository/releases/")
    }
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
}

dependencies {
    compileOnly("org.bstats:bstats-bukkit:3.0.0")
    compileOnly("org.jetbrains:annotations:16.0.2")
    compileOnly("org.spigotmc:spigot-api:1.20.1-R0.1-SNAPSHOT")
    compileOnly("net.milkbowl.vault:VaultAPI:1.6")
    compileOnly("com.sk89q:worldguard:6.1")
    compileOnly("com.sk89q.worldedit:worldedit-bukkit:7.2.11-beta-01")
    compileOnly("com.sk89q.worldedit:worldedit-core:7.2.11-beta-01")
    compileOnly("com.sk89q.worldguard:worldguard-core:7.0.4")
    compileOnly("com.griefcraft.lwc:LWCX:2.2.8")
    compileOnly("com.github.TechFortress:GriefPrevention:16.17.1")
    compileOnly("de.diddiz:logblock:1.16.5.1")
    compileOnly("com.github.Slimefun:Slimefun4:RC-32")
    compileOnly("io.lumine:MythicLib-dist:1.3.1")
    compileOnly("com.acrobot.chestshop:chestshop:3.12.2")
    compileOnly("com.github.TownyAdvanced:Towny:0.98.3.0")
    compileOnly("com.nisovin.shopkeepers:ShopkeepersAPI:2.16.0")
    compileOnly("nl.rutgerkok:blocklocker:1.10.4")
}

// java {
//     withJavadocJar()
// }



// tasks.withType<JavaCompile>() {
//     options.encoding = "UTF-8"
// }

// tasks.withType<Javadoc>() {
//     options.encoding = "UTF-8"
// }

application {
    mainClass.set("brewery.P")
    group = "main.java"
    version = "3.1.1"
    description = "Brewery"
    java.sourceCompatibility = JavaVersion.VERSION_17
}